### ISSUE TITLE
Nightly Broken: 2014-Dec-24

### ISSUE THREAD

**Issue by geneticgrabbag** [nickel-org/nickel.rs#131]
Trying nickel for the first time today on OS X 10.10.1 (14B25).  Seems nightly is broken when running the example from the home page:

    /Users/me/.cargo/git/checkouts/groupable-rs-4437208ae53f1131/master/src/lib.rs:54:2: 54:3 error: expected item, found `;`
    /Users/me/.cargo/git/checkouts/groupable-rs-4437208ae53f1131/master/src/lib.rs:54 );
                                                                                            ^
    /Users/me/.cargo/git/checkouts/rust-plugin-03b112c200450918/master/src/lib.rs:154:6: 154:7 error: expected item, found `;`
    /Users/me/.cargo/git/checkouts/rust-plugin-03b112c200450918/master/src/lib.rs:154     );
                                                                                                ^
    /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.4/src/re.rs:544:21: 544:65 error: use of undeclared type name `std::slice::Iter`
    /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.4/src/re.rs:544     NamesIterNative(::std::slice::Iter<'a, Option<&'static str>>),
                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.4/src/re.rs:545:22: 545:60 error: use of undeclared type name `std::slice::Iter`
    /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.4/src/re.rs:545     NamesIterDynamic(::std::slice::Iter<'a, Option<String>>)
                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to 2 previous errors
    /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.1.4/src/json.rs:209:5: 209:28 error: unresolved import `unicode::str::Utf16Item`. There is no `Utf16Item` in `unicode::str`
    /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.1.4/src/json.rs:209 use unicode::str::Utf16Item;
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error
    Could not compile `groupable`.

Seems at first blush to be an exciting framework.

Thanks in advance!

**Comment by Ryman** [comment]
Closing in favor of #133 as there's more action on the duplicate issue.
