### ISSUE TITLE
Does not compile under Rust 1.0.0 Alpha

### ISSUE THREAD

**Issue by zrneely** [nickel-org/nickel.rs#133]
The library doesn't compile in 1.0.0 alpha. The errors are too long to post here, but I can create a pastebin if necessary.

**Comment by SimonPersson** [comment]
There's a lot of breakage in our dependencies, so it's not only nickel that needs to be fixed. I'll take a look at this after my exams are done, unless someone else fixes it earlier.

**Comment by rgs1** [comment]
FWIW, I got rust-mustache working: https://github.com/nickel-org/rust-mustache/pull/3. I'll check the other deps tomorrow.

**Comment by rgs1** [comment]
FWIW, I almost got groupable working: https://github.com/nickel-org/groupable-rs/pull/1

**Comment by rgs1** [comment]
Got groupable-rs building now: https://github.com/nickel-org/groupable-rs/pull/1

I'll check other deps to see if they are good. Cc: @SimonPersson

**Comment by rgs1** [comment]
This is needed to build: https://github.com/nickel-org/nickel.rs/pull/134/commits (though it's still not building for me)

**Comment by rgs1** [comment]
So with PR #134 it dies because of badly generated code in build/http-315cbfc4b189544c/out/read_method.rs: https://gist.github.com/rgs1/131bc407fe53ea321854.

I'll dig into what generates that file.

**Comment by SimonPersson** [comment]
I don't know why you get an error there. `rust-http` builds fine for me. Have you run `cargo update`? I can't seem to make the `regex!` macro work though, not even the example in their documentation.

**Comment by rgs1** [comment]
yeah regex! is gone, I have more changes coming (one of them is using Regex::new). I got past that error after cargo clean. Will post an update commit later today unless you get to having it build first :-)

**Comment by rgs1** [comment]
More progress here: https://github.com/nickel-org/nickel.rs/pull/135

**Comment by SimonPersson** [comment]
Haha, it was building for a few hours at least! Broken again with the current nightly...

**Comment by rgs1** [comment]
Heh, yeah just saw that. Anymap is the first dep that I see broken, will get to it in a bit!

**Comment by SimonPersson** [comment]
I fixed it up last night, then it was broken again this morning. It seams as if we should expect daily breakage for the moment :)

**Comment by rgs1** [comment]
Ah so Chris Morgan on #rust pointed me to: https://github.com/rust-lang/rust/pull/21745 which apparently is what broke anymap

**Comment by SimonPersson** [comment]
And now it builds again.

**Comment by cburgdorf** [comment]
:+1: Wohooooo! Thanks for all your awesome work on the project everyone!

**Comment by SimonPersson** [comment]
rust-http broke with the latest nightly. Are you working on changing to hyper, @Ryman? I'm wondering if it is worth fixing rust-http or if your work on hyper is close to usable already?

**Comment by Ryman** [comment]
@SimonPersson I don't think it'll be anytime in the next week at least, haven't had a chance to rebase properly yet

**Comment by ninjabear** [comment]
You're really close on the latest nightly (rustc 1.0.0-nightly (dfc5c0f1e 2015-02-18) (built 2015-02-19))

I'm using msys2/win, getting this error,
```
$ cargo build --release
   Compiling http v0.1.0-pre (https://github.com/nickel-org/rust-http.git#4fde95fd)
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\common.rs:182:5: 188:7 error: `concat_idents` is not stable enough for use and is subject to change
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\common.rs:182     test_reads!(http_version,
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\common.rs:183                 "HTTP/25.17\0" => Some((25, 17)),
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\common.rs:184                 "http/1.0\0" => Some((1, 0)),
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\common.rs:185                 "http 1.0\0" => None,
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\common.rs:186                 "HTTP/1.0.\0" => None,
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\common.rs:187                 "HTTP/1.0.\0" => None
```
loads more in the same vein, then

```
                                                                                          ...
error: aborting due to 32 previous errors
Could not compile `http`.

```

applies to cargo build & cargo build --release the same

**Comment by ninjabear** [comment]
it's a fork of rust-http, are there plans to remove this in favour of hyper or whatever? They look like just tests, can we comment them out for the time being?

**Comment by SimonPersson** [comment]
Take a look at the pull requests, we have a solution on the way! :)

Yes, rust-http is going to be replaced soon, there is ongoing work to replace it with Hyper.

**Comment by ninjabear** [comment]
ah yeah sorry as I finished posting that I noticed there were some open pull reqs, sorry!

**Comment by Ryman** [comment]
@ninjabear Should be working now?

**Comment by ninjabear** [comment]
Will have to check later - openssl libs for rust/cygwin not talking to each other now

**Comment by ninjabear** [comment]
but yeah - the original problem has gone now :) don't think this is specific to nickel

**Comment by ninjabear** [comment]
New error now, after cargo clean / update + pull;

rustc 1.0.0-nightly (dfc5c0f1e 2015-02-18) (built 2015-02-19)

cargo build --verbose

```
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:2:15: 2:16 help: did you mean to close this delimiter?
*\http-315cbfc4b189544c\out\read_method.rs:2 pub mod dummy {
                                                                                                            ^
*\http-315cbfc4b189544c\out\read_method.rs:11:83: 11:84 help: did you mean to close this delimiter?
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:11 pub fn read_method<S: Stream>(stream: &mut BufferedStream<S>) -> IoResult<Method> {
                                                                                                                                                                                 ^
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:12:51: 12:52 help: did you mean to close this delimiter?
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:12     let (s, next_byte) = match stream.read_byte() {
                                                                                                                                                 ^
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:175:46: 175:47 help: did you mean to close this delimiter?
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:175         Ok(b'P') => match stream.read_byte() {
                                                                                                                                             ^
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:176:50: 176:51 help: did you mean to close this delimiter?
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:176             Ok(b'A') => match stream.read_byte() {
                                                                                                                                                 ^
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:194:19: 194:20 error: this file contains an un-closed delimiter
*\nickel\target\build\http-315cbfc4b189544c\out\read_method.rs:194                 },
                                                                                                                  ^
Build failed, waiting for other jobs to finish...
Could not compile `http`.
```

and cargo build --release gives something else

```
$ cargo build --release
   Compiling http v0.1.0-pre (https://github.com/nickel-org/rust-http.git#82084c61)
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\server\request.rs:128:21: 128:75 error: couldn't read "*\\nickel\\target\\release\\build\\http-315cbfc4b189544c\\out\\read_method.rs": couldn't open path as file (file not found (The system cannot find the file specified.
); path=*\nickel\target\release\build\http-315cbfc4b189544c\out\read_method.rs; mode=open; access=read)
*\.cargo\git\checkouts\rust-http-1c297591e92637fa\master\src\http\server\request.rs:128         mod dummy { include!(concat!(env!("OUT_DIR"), "/read_method.rs")); }
```

Not quite sure what I'm seeing aside from it really doesn't like that file in rust-http

**Comment by Ryman** [comment]
Travis jumped a nightly, so looks like more failures on the latest nightly, I'll rustup and deal with it.

**Comment by Ryman** [comment]
Dependencies are fixed up now and everythings passing on Travis. 

@ninjabear you might want to try a full `git pull && cargo clean && cargo update && cargo test`.

**Comment by ninjabear** [comment]
I tried with the latest, clean pull etc, still same.

I think its windows/cygwin related - something to do with the path for the include. I'll try to work it out and let you know.

**Comment by ninjabear** [comment]
Something else is broken with rust-http now, looking at the promising work with hyper I doubt its worth fixing. Also this issue I guess is supposed to cover rust-1.0.0alpha, the nightlies are way ahead now, no point supporting rust-alpha imho!

if you replace "transwarp beaming" with "developing rust libs":

https://www.youtube.com/watch?v=jxzYTDX8bIg

:D

**Comment by Ryman** [comment]
Closing as we're now 'stable' on beta :)
