### ISSUE TITLE
Nickel's rust-http fork depends on a rust-openssl that conflicts with the "official" one

### ISSUE THREAD

**Issue by renato-zannon** [nickel-org/nickel.rs#149]
This isn't an issue with nickel but with nickel's rust-http. However, that repo doesn't have the issue tracker enabled, so I decided to open it here.

See this [this stackoverflow question](https://stackoverflow.com/questions/28469061/rusts-openssl-library-is-being-linked-by-more-than-one-dependency-how-can-i-fi) for more details.

It seems to me that changing rust-http to use the crates.io rust-openssl (as rust-postgres does) would solve the issue.

**Comment by thiagopnts** [comment]
This is related to #120
