### ISSUE TITLE
getting 404s because of 'broken pipe' errors

### ISSUE THREAD

**Issue by rgs1** [nickel-org/nickel.rs#152]
With a recent rust nightly:

```shell
$ rustc --version
rustc 1.0.0-nightly (b63cee4a1 2015-02-14 17:01:11 +0000)
```

I am getting a intermittent 404s when serving static files with this error:

```
ERROR:http::server: finishing response failed: broken pipe (Broken pipe)
```

Anyone else seeing this?

**Comment by Ryman** [comment]
I remember seeing that in old builds a while back, but I don't get it with running `examples/example.rs` and visiting 'http://localhost:6767/thoughtram_logo_brain.png' through either spamming browser refresh or via curl. Do you have example code?

**Comment by rgs1** [comment]
@Ryman gone with today's nightly!
