### ISSUE TITLE
Stability 

### ISSUE THREAD

**Issue by dariusc93** [nickel-org/nickel.rs#156]
Hello, I would like to know how stable is nickel vs iron? I know rust itself is still not fully stable but is nickel stable enough to be used in production?

**Comment by cburgdorf** [comment]
I think neither nickel nor iron is more stable than the other. At this
point it's all pretty unstable especially if you ask for production usage.
It's great to have people who are brave enough to use such bleeding edge
stuff in production but I won't tell anybody we are stable as long as the
underlying base isn't.

If you want something really stable you'll have to wait until rust itself
is stable.
Am 22.02.2015 16:04 schrieb "Darius Clark" <notifications@github.com>:

**Comment by dariusc93** [comment]
I wouldnt mine using it in mid production as a form of testing, but I was wondering how stable it was compared to other frameworks out there, even though rust itself is not stable yet.

**Comment by cburgdorf** [comment]
Closing this as a solved question.
