### ISSUE TITLE
Documentation doesn't list what to put in cargo.toml

### ISSUE THREAD

**Issue by ninjabear** [nickel-org/nickel.rs#159]
Not sure if this is anywhere already but if it isn't it would be helpful.

```{toml}
[dependencies.nickel]

git = "https://github.com/nickel-org/nickel.rs.git"

[dependencies.nickel_macros]

git = "https://github.com/nickel-org/nickel.rs.git"
path = "nickel_macros"
```

I came out with this for now but no idea if it's "correct"

**Comment by Ryman** [comment]
The `path` on the second import shouldn't be necessary, cargo does a search throughout the whole repo for Cargo.toml's with libs defined :)

Additional note: we can move nickel_macros into nickel now since we probably aren't going to steer towards compiler plugins as they're not a 1.0 feature.

**Comment by Ryman** [comment]
I think this is covered now :)
