### ISSUE TITLE
Mustache partials not working

### ISSUE THREAD

**Issue by ninjabear** [nickel-org/nickel.rs#160]
https://github.com/ninjabear/nickel-bootstrap/tree/master/templates

In here I have some mustache partials set up, but I'm not entirely clear on how nickel would use them (it doesn't appear to automatically). 

I had a quick look at the code, not sure where or if it has been implemented.

**Comment by ninjabear** [comment]
I tried using this https://github.com/erickt/rust-mustache directly too - not compiling at the moment. 

The test for partials is here; https://github.com/erickt/rust-mustache/blob/master/src/template.rs#L474

**Comment by SimonPersson** [comment]
The upstream version haven't compiled in a long time and none of the PRs where requested.

The tests for partials is there in our branch too and passes. Maybe you can take a look and see if the test case is not good enough or if you're doing something wrong.

**Comment by Ryman** [comment]
It likely has something to do with the changes I made for migrating to the new fs/io apis! That touched some logic for partial file loading (and if the files are not found then mustache treats them as empty strings by current design)

**Comment by ninjabear** [comment]
Presumably now nickel-mustache is the "official" version rather than a fork we should fix this there?

**Comment by Ryman** [comment]
@ninjabear Yeah :)
