### ISSUE TITLE
directories not handled correctly after porting to hyper

### ISSUE THREAD

**Issue by rgs1** [nickel-org/nickel.rs#165]
Mostly sure this wasn't a problem with rust-http, but requesting a directory from a path served via StaticFilesHandler hangs the server. As an example, this hangs forever:

```
$ mkdir examples/assets/foo
$ touch examples/assets/foo/bar
$ target/examples/example
$ curl http://localhost:6767/foo
```
Ideas? Not sure if this Hyper or nickel.rs specific will dig in a bit more.

**Comment by rgs1** [comment]
Yeah, from strace I see we don't check if the static file is a directory:

```
) = 38
[pid 17903] stat("examples/assets/foo", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
[pid 17903] open("examples/assets/foo", O_RDONLY) = 15
[pid 17903] read(15, 0x7fd2d4be7c48, 65536) = -1 EISDIR (Is a directory)
[pid 17903] close(15)                   = 0
```

**Comment by rgs1** [comment]
So in StaticFilesHandler#with_file we do:

```rust
        if let Some(path) = relative_path {
            let path = self.root_path.join(path.as_path());
            if path.exists() {
                return Ok(Halt(try!(res.send_file(&path))));
            }
        };
```

I think we should extend StaticFilesHandler with a new constructor option dir_listing: Boolean, and if that's on serve the dir listing, otherwise return 404. Thoughts?

**Comment by rgs1** [comment]
Possible fix: https://github.com/nickel-org/nickel.rs/pull/166

**Comment by Ryman** [comment]
Overlap with #154

**Comment by cburgdorf** [comment]
Closing as part of a clean up of our issue tracker. Anyone please free to reopen for further discussion.
