### ISSUE TITLE
error reading status line

### ISSUE THREAD

**Issue by rgs1** [nickel-org/nickel.rs#167]
Seeing this when accessing a nickel app via apache's mod_proxy:

```
The timeout specified has expired: proxy: error reading status line from remote server localhost:8080
```

Might be a new thing (i.e.: after the hyper port). Has anyone else seen this? Looking with GDB, I see the worker thread hanged on CloneTcpStream#read().

**Comment by Ryman** [comment]
This is probably a keepalive issue related to https://github.com/hyperium/hyper/issues/368.

According to some searching, the temporary fix would be: 'There is a way to de-activate keep-alive for back-end connections: setting the proxy-nokeepalive environment variable (see the "Protocol Adjustments" section of the mod_proxy manual pages)'

**Comment by rgs1** [comment]
yeah saw that thread! thanks @Ryman!

**Comment by rgs1** [comment]
closing since this seems to be hyper (and disabling keep-alive is a valid workaround for now).
