### ISSUE TITLE
missing crate rustc-serialize

### ISSUE THREAD

**Issue by bitloner** [nickel-org/nickel.rs#169]
I cannot compile a nickel web app because I am missing the `rustc-serialize` dependency.

Here's a snippet of my Cargo.toml

[dependencies]

csv = "*"
rustc-serialize = "*"

[dependencies.nickel]

git = "https://github.com/nickel-org/nickel.rs.git"

[dependencies.nickel_macros]

git = "https://github.com/nickel-org/nickel.rs.git"

**Comment by SimonPersson** [comment]
I think you should specify a version, no?

The following line works for me:
```
rustc-serialize = "*"
```
What error are you getting?

**Comment by ninjabear** [comment]
https://github.com/ninjabear/nickel-bootstrap/blob/master/Cargo.toml

**Comment by bitloner** [comment]
Sorry I added that `rustc-serialize = "*"` line to get around it. The getting started guide seems incorrect as it's not a one-liner dependency; I had to add `rustc-serialize` and `nickel_macros` manually.

**Comment by Ryman** [comment]
Added a note to README in https://github.com/nickel-org/nickel.rs/commit/fa2b31f14ff4a632e7e203f70a6e3653977c8f4d and mentioned on [nickel.rs](http://nickel.rs/#json-handling) too.
