### ISSUE TITLE
can't compile with rust 1.0 beta

### ISSUE THREAD

**Issue by daogangtang** [nickel-org/nickel.rs#179]
hi, nickel now can't compile with rust 1.0 beta.

   Compiling url v0.2.29
/home/mike/.cargo/git/checkouts/groupable-rs-4437208ae53f1131/master/src/lib.rs:1:1: 1:25 error: unstable feature
/home/mike/.cargo/git/checkouts/groupable-rs-4437208ae53f1131/master/src/lib.rs:1 #![feature(collections)]
                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
   Compiling num_cpus v0.1.0
   Compiling openssl-sys v0.5.5
   Compiling time v0.1.24
   Compiling typemap v0.1.0
Build failed, waiting for other jobs to finish...
/home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.26/src/lib.rs:370:34: 370:48 error: unstable feature
/home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.26/src/lib.rs:370 #![cfg_attr(feature = "pattern", feature(core))]
                                                                                                                        ^~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `groupable`.

To learn more, run the command again with --verbose.

**Comment by nicolai86** [comment]
:+1:

**Comment by Ryman** [comment]
Should be working now, feel free to reopen if issues persist!
