### ISSUE TITLE
error: an external crate named `nickel` has already been imported into this module

### ISSUE THREAD

**Issue by preradio** [nickel-org/nickel.rs#181]
The code sample on nickel.rs in #4 gives an error if copied directly because the crate is called twice:

extern crate nickel;

#[macro_use] extern crate nickel_macros;
extern crate nickel;

Not sure where to post this so here it is :)

Jason

**Comment by Ryman** [comment]
Thanks for the report, should be fixed soon!

**Comment by Ryman** [comment]
Fixed: http://nickel.rs/getting-started.html
