### ISSUE TITLE
can't find crate for `nickel_macros`

### ISSUE THREAD

**Issue by jamm** [nickel-org/nickel.rs#183]
after installing nickel.rs as a Cargo crate, I can't compile code from examples. Always error `can't find crate for 'nickel_macros'`

nickel 0.2.0
rust 1.0.0 beta

**Comment by saggit** [comment]
@jamm as far as i know, if you put nicel_macros(download a copy) in the same level with src, it will work.

**Comment by cburgdorf** [comment]
Ah, dann. I didn't test that out. I think we should move the macros into their own repository. @ryman what do you think?

**Comment by lambdaburrito** [comment]
A quick interim solution is to add as an additional dependency like:

[dependencies.nickel_macros]
git = "https://github.com/nickel-org/nickel.rs.git"

**Comment by jamm** [comment]
thanks for workarounds. Please make it working out of the box :)
