### ISSUE TITLE
examples from nickel.rs site doesn't work at all

### ISSUE THREAD

**Issue by jamm** [nickel-org/nickel.rs#184]
and it's not surprising because first line is "extern crate http;" and it means that docs are obsolete.

**Comment by ninjabear** [comment]
A lot of the docs could do with a spruce up - the readme for example is very long. Nickel is actually easier to use than it makes out.

http://www.sinatrarb.com/

^ Here's a good example of a main page/starter splash imo. Then they go on to have a more detailed readme as an "intro" http://www.sinatrarb.com/intro.html

**Comment by ninjabear** [comment]
The docs spruce up could include #159

**Comment by Ryman** [comment]
Updated all examples on [nickel.rs](http://nickel.rs) to 0.5
