### ISSUE TITLE
arithmetic operation overflowed

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/nickel.rs#185]
The following error occurred when trying to run the following server:

```
thread '<main>' panicked at 'arithmetic operation overflowed', /Users/cburgdorf/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.3.11/src/server/mod.rs:90
```

```rust
extern crate nickel;
#[macro_use] extern crate nickel_macros;

use nickel::{ Nickel };
use nickel::router::http_router::HttpRouter;

fn main() {
    let mut server = Nickel::new();

    server.get("/bar", middleware!("This is the /bar handler"));
    server.listen("127.0.0.1:6767");
}

```

**Comment by cburgdorf** [comment]
I'm pretty sure we are seeing this https://github.com/seanmonstar/num_cpus/issues/2

**Comment by lambdaburrito** [comment]
Yeah, that's the reason why nickel.rs apps are not running on macs. I've submitted a pull requests so hopefully will be fixed soon. I would greatly appreciate if you would look at https://github.com/nickel-org/nickel.rs/issues/186 until my fix is merged; not sure if it's a bug or just not using the macro properly.

**Comment by lambdaburrito** [comment]
It's patched now so seems fine to close now.
