### ISSUE TITLE
Template changes but request still keeps opening old. Needs rerunning. 

### ISSUE THREAD

**Issue by whispermemory** [nickel-org/nickel.rs#193]

**Comment by whispermemory** [comment]
- 1-| #[macro_use]
|- 2-| extern crate nickel;
|- 3-|
|- 4-| use nickel::{Nickel, Request, Response, HttpRouter, MiddlewareResult};
|- 5-| use std::collections::HashMap;
|- 6-|
|- 7-| fn main() {
|- 8-|     let mut server = Nickel::new();
|- 9-|
|-10-|     fn handler<'a>(_: &mut Request, res: Response<'a>) -> MiddlewareResult<'a> {
|-11-|         let mut data = HashMap::<&str, &str>::new();
|-12-|         data.insert("name", "user");
|-13-|         res.render("templates/index.html", &data)
|-14-|     }
|-15-|
|-16-|
|-17-|     server.get("/", middleware!(@handler));
|-18-|
|-19-|     server.listen("127.0.0.1:6767");
|-20-| }


I modified templates/index.html but  it wont take effects until rerunning the app.

**Comment by whispermemory** [comment]
|-1-| #[macro_use]
|-2-| extern crate nickel; 
|-3-| 
|-4-| use nickel::{Nickel, Request, Response, HttpRouter, MiddlewareResult}; 
|- 5-| use std::collections::HashMap;
|- 6-|
|- 7-| fn main() {
|- 8-| let mut server = Nickel::new(); 
|- 9-| 
|-10-| fn handler<'a>(_: &mut Request, res: Response<'a>) -> MiddlewareResult<'a> { 
|-11-| let mut data = HashMap::<&str, &str>::new();
|-12-| data.insert("name", "user"); 
|-13-| res.render("templates/index.html", &data) 
|-14-| } 
|-15-|
|-16-| 
|-17-| server.get("/", middleware!(@handler)); 
|-18-| 
|-19-| server.listen("127.0.0.1:6767");
 |-20-| }

**Comment by Ryman** [comment]
@whispermemory Currently templates are cached after they are compiled, I think it would be a good feature if they were recompiled on change when not running in release mode. 

Also if you want to post code in github you can use three backticks ``` around your code.
