### ISSUE TITLE
Last example not work

### ISSUE THREAD

**Issue by Codenator81** [nickel-org/nickel.rs#203]
// go to http://localhost:6767/content-type to see this route in action
            router.get("/content-type", middleware! { |request, mut response|
              response.content_type(MediaType::Json);
              "{'foo':'bar'}"
       });

this example work when in example from nickel.rs repo but when I copy to my app I got 
error

    src/main.rs:54:51: 54:89 error: the type of this value must be known in this context
    src/main.rs:54                                                   response.content_type(MediaType::Json);<br>
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <nickel macros>:1:1: 1:27 note: in expansion of as_block!
    <nickel macros>:13:1: 13:31 note: expansion site
    <nickel macros>:1:1: 16:47 note: in expansion of middleware!
    <nickel macros>:16:1: 16:43 note: expansion site
    <nickel macros>:1:1: 16:47 note: in expansion of middleware!
    src/main.rs:53:37: 56:6 note: expansion site
    error: aborting due to previous error
    Could not compile `nickel-demo`.

I tray copy all example.rs just to my main.rs and got the same error

**Comment by Codenator81** [comment]
<code>
fn content_type<'a>(_: &mut Request, mut res: Response<'a>) -> MiddlewareResult<'a> {<br />
        res.content_type(MediaType::Json);
        res.send( "{'foo':'bar'}")
}
</code>

**Comment by Ryman** [comment]
@Codenator81 Sorry, the crates.io version which I assume you're depending on does not yet have that functionality! If you wish to use the latest changes you'll need a to use either a local override or a git dependency.

@cburgdorf Can you push an update?

**Comment by Codenator81** [comment]
[dependencies.nickel]
    
    git = "https://github.com/nickel-org/nickel.rs.git"

I using git version in my Cargo.toml

**Comment by Ryman** [comment]
Does `cargo update` work? Else, can you post a small example that I can test? I've tried pulling out the sample and it worked for me.

**Comment by Codenator81** [comment]
```rust
#[macro_use]
extern crate nickel;

use nickel::{Nickel, Request, Response, HttpRouter, MiddlewareResult, MediaType};

fn main() {
    let mut server = Nickel::new();
    let mut router = Nickel::router();
    router.get("/content-type", middleware! { |request, mut response|
        response.content_type(MediaType::Json);
        "{'foo':'bar'}"
    });
    server.utilize(router);
    server.listen("127.0.0.1:8080");
}
```

Any way Cargo update help

**Comment by cburgdorf** [comment]
Just wanted to let you know here that we just pust version [0.3.0](https://github.com/nickel-org/nickel.rs/blob/master/changelog.md#v030-2015-05-01) to crates.io that contains everything that's in latest master.

**Comment by Codenator81** [comment]
Thanks
