### ISSUE TITLE
server hanging after running for over 30 seconds

### ISSUE THREAD

**Issue by freiguy1** [nickel-org/nickel.rs#218]
I've a Debian server and I'm trying to run the release version of my [simple web application](https://github.com/freiguy1/schedule-gen-web) using nickel.rs, and after it's been running for as little as 30 seconds, it stops responding.  I added a middleware to log every request, and that doesn't even get reached.  When I use `curl` on the server pointed to localhost, that acts the same way as the browsers.  They just spin indefinitely.

The worst problem is that I try the same code/same version of rust on a different Ubuntu server and it never hangs.

Any idea how to remedy this problem?

**Comment by ninjabear** [comment]
If you open a socket using another tool on that port, does the same problem occur? Lots of problems like this I've found are due to router problems, especially if any NAT traversal is taking place somewhere

**Comment by freiguy1** [comment]
Good thoughts, however if you're talking physical router problems, I thought my `curl localhost:3000` would eliminate that from the equation.  As far as running it on a different port, I can try. The whole story is that I am hosting it on port 3000 and using a virtual host in apache to route a url to localhost:3000.  So I'm actually only hitting it through port 80 when accessing it remotely.  And I've many things (no rust webapps *yet* though) hosted on other ports using virtual hosts @ port 80 w/ apache on that machine - so that layer shouldn't be the issue.

**Comment by ninjabear** [comment]
Oh ok. 

Have you tried subbing out your code for a nickel hello world and seeing if you get the same result? Just trying to isolate the problem a bit more. 

```rust
#[macro_use] extern crate nickel;

use nickel::Nickel;

fn main() {
    let mut server = Nickel::new();

    server.utilize(router! {
        get "**" => |_req, _res| {
            "Hello world!"
        }
    });

    server.listen("127.0.0.1:6767");
}
```

Is it after a certain number of requests? Is it linked to the number of requests at all do you think?

**Comment by ninjabear** [comment]
The thing that steered me towards it being a config issue was that the same code works fine on your ubuntu machine - odd because everything apart from the config should be the same. 

Anything special in /etc/hosts or iptables?

**Comment by freiguy1** [comment]
Thanks for the help! I think I'm leaning toward blaming apache as of now. After checking the apache error logs, I get something similar to this [serverfault stackoverflow problem](http://serverfault.com/questions/206738/intermittent-error-when-using-mod-proxy-to-do-reverse-proxy-to-soap-service). And after the suggested changes, it's working as of now! I'm curious as to what's different between the nickel server and the other types of sites I'm running (ghost blog and a few Play! Framework applications).

**Comment by Ryman** [comment]
@freiguy1 If apache is using keepalive, then it's likely causing issues due to https://github.com/hyperium/hyper/issues/368 (Apache isn't really at fault, just keepalive being badly handled)

Let me know if you find a different root cause though!

**Comment by freiguy1** [comment]
@Ryman Ok, that makes a lot of sense.  That answers my question

> ...what's different between the nickel server and the other types of sites I'm running

Thanks for the input!
