### ISSUE TITLE
Still possible to call Response::send_file directly with the middleware! macro?

### ISSUE THREAD

**Issue by tarcieri** [nickel-org/nickel.rs#223]
I was using this successfully in previous incarnations of Nickel, but can't seem to get it to work now...

```rust
fn main() {
  let mut server = Nickel::new();

  server.get("/", middleware! { |_request, response|
    response.send_file(&Path::new("frontend/setup.html")).ok()
  });
  server.utilize(StaticFilesHandler::new("frontend/"));
  server.listen("127.0.0.1:3000")
}
```

I would like for `/` to be variadic based on certain conditions. Is there a way to do this with the `middleware!` macro?

Should I just read the file contents myself and return a string?

**Comment by Ryman** [comment]
You should be able to use `return response.send_file(..)`, it's a bit of a trick about how the macro expands, if you need to return `MiddlewareResult` rather than a `ResponseFinalizer/Responder` you can do an early return. 

Can you elaborate on what you mean by you want `/` to be variadic? Do you mean returning different types of data based on different conditions?

**Comment by tarcieri** [comment]
> You should be able to use return response.send_file(..)

Looks like `send_file` returns an `Option` and it's expecting a `Result`?

src/main.rs:10:12: 10:70 error: mismatched types:
 expected `core::result::Result<nickel::middleware::Action<nickel::response::Response<'a>, nickel::response::Response<'a, hyper::net::Streaming>>, nickel::nickel_error::NickelError<'a>>`,
    found `core::option::Option<nickel::middleware::Action<nickel::response::Response<'_>, nickel::response::Response<'_, hyper::net::Streaming>>>`
(expected enum `core::result::Result`,
    found enum `core::option::Option`) [E0308]

> Do you mean returning different types of data based on different conditions?

Yeah, basically I have two different static files and want to choose which is served depending on whether or not first-time setup is complete.

**Comment by Ryman** [comment]
If you haven't changed since the above code snippet, you have `.ok()` at the end of the line.

You can just branch to decide filename if that's all you need?

**Comment by tarcieri** [comment]
Removing the `.ok()` fixed the problem, thanks!
