### ISSUE TITLE
Static files and url parameters

### ISSUE THREAD

**Issue by JadeSnail** [nickel-org/nickel.rs#224]
I'm trying to use mathjax on my server. I install it locally and serve the directory using StaticFilesHandler but mathjax tries to access files such as /MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML which fails to resolve.

Is that intended ? If so, how can I make this work ?

**Comment by Ryman** [comment]
@JadeSnail Thanks for raising the issue, can you try testing against #225? 

In your cargo.toml:
```
[dependencies.nickel]
git = "https://github.com/Ryman/nickel.rs"
branch = "gh224"
```

**Comment by JadeSnail** [comment]
That seems to work.
