### ISSUE TITLE
static file handler hangs on mass file serve

### ISSUE THREAD

**Issue by daa84** [nickel-org/nickel.rs#226]
In some cases when static file handler serve multiple files (js, css, html) time to time it hangs. this problem depends on server that used to run application. I find that problem is inside hyper, instead of listen i use listen_threads and it solves problem. So maybe better to update hyper to somthig >0.4? or allow user to configure hyper server settings?

**Comment by daa84** [comment]
Also update to hyper 0.5.0 does not solve problem, only threaded listener does :(

**Comment by Ryman** [comment]
Out of interest, what are your parameters to `listen_threads`? Because hyper does in fact call that under the hood for `listen`. Do you by any chance have a single core machine? (But I agree that we should expose more flexibility here)

From [here](http://hyper.rs/hyper/src/hyper/server/mod.rs.html#62-66): 
```rust
/// Binds to a socket and starts handling connections.
pub fn listen<T: ToSocketAddrs>(self, addr: T) -> ::Result<Listening> {
    self.listen_threads(addr, num_cpus::get() * 5 / 4)
}
```

**Comment by daa84** [comment]
Hello, yes i check also this code and looks like problem in hyper server that can't process to much queries when have small number of threads.
I test it on 3 computers:
* linux 4 core cpu - works perfectly without any threads changes.
* windows 4 core cpu - here problem occur, but set threads count to 10 solves it
* linux 1 core cpu - it really does not work with multi request.

so i think it just not usable with multiuser environment currently.

**Comment by daa84** [comment]
ok, same issue on iron that also use hyper:
https://github.com/iron/iron/issues/335

**Comment by cburgdorf** [comment]
Closing as part of a clean up of our issue tracker. Anyone please free to reopen for further discussion.
