### ISSUE TITLE
can't find crate for `rustc_serialize`

### ISSUE THREAD

**Issue by JerrieLau** [nickel-org/nickel.rs#227]
I cannot compile a nickel demo app because I am missing the rustc-serialize dependency.
Here's a snippet of my Cargo.toml
[dependencies]
nickel = "0.5.0"

Here's the error:
src/main.rs:1:1: 1:30 error: can't find crate for `rustc_serialize`
src/main.rs:1 extern crate rustc_serialize;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `nickel-demo`.

**Comment by Ryman** [comment]
Hi @JerrieLau, sorry I missed this issue. Did you get this working?

You need to add `rustc-serialize = "*"` to your dependencies in the `Cargo.toml` file.

cc #169

**Comment by Ryman** [comment]
Added a note to README in https://github.com/nickel-org/nickel.rs/commit/fa2b31f14ff4a632e7e203f70a6e3653977c8f4d and mentioned on [nickel.rs](http://nickel.rs/#json-handling) too.
