### ISSUE TITLE
ab time

### ISSUE THREAD

**Issue by jiaojian** [nickel-org/nickel.rs#230]
I use ab to test demo[Your first nickel app], but ab is timeout

error:
Benchmarking 127.0.0.1 (be patient)...apr_pollset_poll: The timeout specified has expired (70007)

OS:4.0.4-202.fc21.x86_64
rustc version:rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

**Comment by Ryman** [comment]
Hi @jiaojian,

Are you using `-k` to run `ab`?
