### ISSUE TITLE
Nested response.render() calls 

### ISSUE THREAD

**Issue by schickst** [nickel-org/nickel.rs#231]
Hello, 

I am just starting with rust. In my experience with other web frameworks it is usually possible to create nested templates. Below is an example of what I mean. Basically I want to render a template and use it as variable content for another template. Is something like this possible with nickel?

File template.tpl:
``` html
<html>
  <header></header>
  <body>{{ content }}</body>
</html>
```

File page.tpl:
``` html
<h3>Test</h3>
<p>Lorem Ipsum</p>
```

Part of file main.rs:
``` rust
    fn handler<'a>(_request: &mut Request, response: Response<'a>) -> MiddlewareResult<'a> {
        let mut data = HashMap::<&str, &str>::new();
        let mut some_other_data = HashMap::<&str, &str>::new();
        let content =  Response::render("page.tpl", &some_other_data);
        data.insert("content", content);

        response.render("./template.tpl", &data)
    }
    server.get("/", handler);
```

Regards, 
Stefan

**Comment by Ryman** [comment]
Hi @schickst,

Yeah, this is possible using mustache partials, you can see an example of them [here](https://github.com/ninjabear/nickel-bootstrap/blob/master/templates/index.mustache) and see the mustache syntax documentation [here](http://mustache.github.io/mustache.5.html#Partials).

Please reopen if there is still a problem :)
