### ISSUE TITLE
hyper v0.4.0 doesn't build on rust nightly

### ISSUE THREAD

**Issue by dginev** [nickel-org/nickel.rs#239]
On ```rustc 1.3.0-nightly (7ea2674c7 2015-07-13)```, building nickel.rs fails for me, due to hyper v0.4.0 not building anymore.

Have you thought of upgrading to the latest hyper, or is there something I can do to avoid this problem? Thanks!

 Here is the error message:
> $ cargo build
   Compiling hyper v0.4.0
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:436:1: 436:25 error: missing documentation for a constant
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:436 pub const SP: u8 = b' ';
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2:9: 2:21 note: lint level defined here
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2 #![deny(missing_docs)]
                                                                                                   ^~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:437:1: 437:26 error: missing documentation for a constant
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:437 pub const CR: u8 = b'\r';
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2:9: 2:21 note: lint level defined here
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2 #![deny(missing_docs)]
                                                                                                   ^~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:438:1: 438:26 error: missing documentation for a constant
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:438 pub const LF: u8 = b'\n';
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2:9: 2:21 note: lint level defined here
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2 #![deny(missing_docs)]
                                                                                                   ^~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:439:1: 439:27 error: missing documentation for a constant
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:439 pub const STAR: u8 = b'*';
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2:9: 2:21 note: lint level defined here
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2 #![deny(missing_docs)]
                                                                                                   ^~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:440:1: 440:46 error: missing documentation for a constant
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/http.rs:440 pub const LINE_ENDING: &'static str = "\r\n";
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2:9: 2:21 note: lint level defined here
/home/dreamweaver/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.4.0/src/lib.rs:2 #![deny(missing_docs)]
                                                                                                   ^~~~~~~~~~~~
error: aborting due to 5 previous errors
Could not compile `hyper`.

**Comment by Ryman** [comment]
Covered by #237, just haven't merged that yet as there were a few things waiting for a version bump. Might merge later today.

**Comment by dginev** [comment]
Oh, this is awesome news, thanks! Will keep an eye on that issue.

**Comment by Ryman** [comment]
Published 0.6, please reopen if you still have issues.

**Comment by dginev** [comment]
Thank you, works like a charm again!

**Comment by Ticki** [comment]
Seems to be broken again...

**Comment by Ryman** [comment]
@Ticki Which compiler & nickel versions do you see the issue with?

**Comment by Ticki** [comment]
It's fixed after I deleted `target`.
