### ISSUE TITLE
Add example handling form data

### ISSUE THREAD

**Issue by Ryman** [nickel-org/nickel.rs#240]

**Comment by AlexanderElias** [comment]
Example beneath.

I believe we still need a method for decoding and parsing the url, correct? 


<strong>Main.rs</strong>
```
#[macro_use] extern crate nickel;
use nickel::{Nickel, HttpRouter, StaticFilesHandler, FaviconHandler};
use std::collections::HashMap;

// Required For Post
extern crate hyper;
use std::io::Read;
use hyper::Client;
use hyper::header::Connection;
// Required For Post

fn main() {

    //Implement A Server
    let mut server = Nickel::new();


    server.get("/contact", middleware! { |req, mut res|

        let mut data = HashMap::new();
        data.insert("title","Contact Form");

        return res.render("views/contact.html", &data)
    });


    server.post("/confirmation", middleware!{ |req, res|

        let mut form_data = String::new();
        req.origin.read_to_string(&mut form_data);

        println!("{}", form_data);
    });

    server.listen("0.0.0.0:3000");
}
```

<br/>
<br/>

<strong>Contact.html</strong>
```
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>{{title}}</title>
</head>
<body>
                        <form>
                              <input type="text" name="firstname" placeholder="First Name" autofocus>
                              <input type="text" name="lastname" placeholder="Last Name">
                              <input type="tel" name="phone" placeholder="Phone #">
                              <input type="email" name="email" placeholder="Email">
                              <button type="submit" formenctype="application/x-www-form-urlencoded" formaction="/confirmation" formmethod="post">SEND</button>
                        </form>
</body>
```

<br/>
<br/>

<strong>CMD Output</strong>
```
firstname=alex&lastname=elias&phone=77777777&email=me%40yes.com
```

**Comment by Ryman** [comment]
@AlexanderElias Looks like the basic idea, yes there is a method used in the `QueryString` parsing which could be reused if re-export:)

I think we may want to go a bit further and do the boilerplate as a plugin similar to how `QueryString` is currently. (we may want a secondary plugin though to cache the result of reading the body of a request, which is also used in the json plugin)

Do you want to try to PR something like this? (or your own take on it, is welcomed!) If not can I use your example as a basis for whenever I get to it?

**Comment by AlexanderElias** [comment]
Sorry it took so long to get back to you. I believe this is what you were suggesting. Also I started working on my own parser it works thus far it just needs to be able to encode symbols characters. Let me know if we need one.

**Comment by anvie** [comment]
Is my approach for handling form data acceptable? 
https://github.com/anvie/nickel.rs/commit/c001383028c973e61d733e13c52cf3c14b61f9d7

**Comment by cburgdorf** [comment]
Hey @anvie, that looks quite good to me but @Ryman may have other notes. Would you mind preparing a PR for that so we can comment and iterate there?

**Comment by Ryman** [comment]
@anvie Looks like a good start, I think we need to introduce an extra layer somewhere though, as I think this will blow up if you try to call `form_data` and then call `json_as` (as they both read the body out of the `HyperRequest` and I'm unsure what happens if you try that twice!). The `Request` api could really do with a prune to make it a bit safer to use!

I think this could be isolated in a separate crate (e.g. nickel-formdata) so it could be iterated on quicker without having to continually bump nickel's version-number. @cburgdorf What do you think? Otherwise I'm happy enough to review a PR and give feedback there.

**Comment by cburgdorf** [comment]
Yes, I agree. Just as we did with `cookies` and `session`. The only thing I worry about is that we need to publish those on cargo, too. We probably need to tweak our release process a bit soon to overcome this.

**Comment by jolhoeft** [comment]
This was merged in a while ago, and exists at examples/form_data/form_data.rs
