### ISSUE TITLE
How can I hot reload the changes without restart the server?

### ISSUE THREAD

**Issue by mrkaspa** [nickel-org/nickel.rs#242]

**Comment by Ryman** [comment]
Currently this is unsupported, you might be able to hack something together using [guard](https://github.com/guard/guard) or something similar if required :)

**Comment by mrkaspa** [comment]
Ok good I'l give it a try

**Comment by cburgdorf** [comment]
Closing as part of a clean up of our issue tracker. Anyone please free to reopen for further discussion.

**Comment by anvie** [comment]
Hi @mrkaspa If you're using Linux you can use inotify, like this: https://github.com/anvie/sso/blob/master/etc/script/devmon.sh
