### ISSUE TITLE
request.query() is gone?

### ISSUE THREAD

**Issue by dginev** [nickel-org/nickel.rs#244]
I was looking at the examples here:
https://github.com/nickel-org/nickel.rs/blob/master/examples/macro_example.rs#L114

As I am trying to figure out how to access the query parameters in GET requests. I'm similarly failing in getting query parameters from the bodies of POST requests.

If this is a regression, just wanted to let you know. If it isn't, I would be really grateful if you give me a pointer to the current way of dealing with query parameters (and you can of course close this issue).

Thanks, loving nickel overall!

**Comment by Ryman** [comment]
I'm not sure I understand exactly what you're doing, the example you linked works fine for me?

To be clear, do mean query parameters as in `http://host.com/path?foo=bar` where `foo` is a query parameter. Or are you talking about params such as in the router paths, where `id` is a param in `/:id`.

Can you give an example of what data you're working with, and what the expected values would be?

**Comment by dginev** [comment]
I am trying to obtain the ```?foo=bar``` parameters right now. 

What I am trying isn't verbatim the example, so I may have wrong expectations. Here is an example:

```rust
    server.get("/test", middleware! { |request, mut response| 
      let query = request.query();
     });
```

Which gives me the error:
```
examples/frontend.rs:85:27: 85:34 error: no method named `query` found for type `&'r mut nickel::request::Request<'b, 'a, 'b>` in the current scope
examples/frontend.rs:85       let query = request.query();
                                                  ^~~~~~~
<nickel macros>:1:1: 1:27 note: in expansion of as_block!
<nickel macros>:10:12: 10:42 note: expansion site
note: in expansion of closure expansion
<nickel macros>:9:1: 10:54 note: expansion site
<nickel macros>:1:1: 10:62 note: in expansion of _middleware_inner!
<nickel macros>:2:1: 2:64 note: expansion site
<nickel macros>:1:1: 7:46 note: in expansion of middleware!
examples/frontend.rs:84:31: 129:6 note: expansion site
examples/frontend.rs:85:27: 85:34 help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
examples/frontend.rs:85:27: 85:34 help: candidate #1: use `nickel::query_string::QueryString`
error: aborting due to previous error
```

I tried importing the trait too, but it complained it was private. So if you could point me to the recommended way of getting the parameters, I would be good to go.

**Comment by Ryman** [comment]
Ah, the error message is half-correct but it's giving a path to a private module.. seems like a bug.

It's re-exported publicly as `nickel::QueryString`, does that work for you?  Sorry for the confusion!

**Comment by dginev** [comment]
Of course, as long as ```request.query()``` works, I am happy with importing any necessary trait. Thanks a lot for the quick response!

**Comment by dginev** [comment]
Works like a charm, sorry I didn't realize I was missing the trait sooner, it's a bit unfortunate that the most informative part of the error message was at its bottom.

Closing here, "user problem".

**Comment by Ryman** [comment]
No worries :)

For reference, here's an open issue for the problem you encountered with private paths in the error message: https://github.com/rust-lang/rust/issues/26454
