### ISSUE TITLE
Improve ergonomics of redirects

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/nickel.rs#248]
Writing handler that redirect is a bit of a pain currently (unless I'm doing it wrong).

- one has to explicitly add `hyper``
- one has to import `hyper::header::Location;` and `nickel::status::StatusCode`
- and then write:

```rust
server.get("/login",middleware! { |_, mut res |
        res.set(StatusCode:: TemporaryRedirect)
        .set(Location("http://nickel.rs".to_owned()));
        ""
    });
```

I'd love to have something as simple as:

```rust
server.get("/login",middleware! { |_, mut res |
        res.redirect("http://nickel.rs")
    });
```

**Comment by Ryman** [comment]
I actually have a half finished branch with this but have held off on finishing it until landing something like #246 as it'll need changed immediately after that lands (and one part isn't possible without), summary of api is:

* redirect(target)
* redirect_permanently(target)
* redirect_with(target, status_code)
* redirect_back() - this is the one that benefits from environment (using the referrer header), so I have this one in mind but haven't actually written it

I might be able to clean it up and push for review later/tomorrow.

**Comment by cburgdorf** [comment]
That sounds awesome! I'm happy to check it out. I'm actually in the process of writing a real production application for my company with nickel. I expect to run into one or two issues along the way. It will probably help us to polish the APIs.

**Comment by Ryman** [comment]
See last commit here: https://github.com/Ryman/nickel.rs/tree/redir

**Comment by cburgdorf** [comment]
Looks pretty much perfect (except for the unimplemented part) :+1:
