### ISSUE TITLE
How to parse JSON with optional fields?

### ISSUE THREAD

**Issue by flosse** [nickel-org/nickel.rs#250]
[Here](https://github.com/nickel-org/nickel.rs/blob/3c506d08033477a779d1ae2c184525a21f571b68/examples/macro_example.rs#L108) is an example how to parse a POST request with JSON data.

The struct looks like this:
```rust
#[derive(RustcDecodable, RustcEncodable)]
struct Person {
    firstname: String,
    lastname:  String,
}
```
and the parsing is trivial:
```rust
let person = request.json_as::<Person>().unwrap();
```
But how can I handle requests with optional fields?
E.g. if my `Person` has an ID:

```rust
#[derive(RustcDecodable, RustcEncodable)]
struct Person {
    id: u32, 
    firstname: String,
    lastname:  String,
}
```
but this ID will be created by the DB after the request was made. How can I parse the JSON data that has not `id` field?

**Comment by SimonPersson** [comment]
> But how can I handle requests with optional fields?

You're almost spelling it out yourself! Like this:
```
#[derive(RustcDecodable, RustcEncodable)]
struct Person {
    id: Option<u32>, 
    firstname: String,
    lastname:  String,
}
```

**Comment by flosse** [comment]
@SimonPersson thanks a lot!
