### ISSUE TITLE
How to call Halt from custom Middleware

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/nickel.rs#252]
Yay, I've been away to long ;)

I got stuck half way when I tried to write this basic custom middleware for my application.

```rust
use nickel::*;
use nickel::status::StatusCode;
use hyper::header::{Location};

struct Auth;

impl Middleware for Auth {
    fn invoke<'a>(&self, req: &mut Request, res: Response<'a>) -> MiddlewareResult<'a> {
        // I know that's not the way to go, it's just for learning purpose and to
        // take one step at a time ;)
        if let Some(_) = req.query().get("session") {
            Ok(Continue(res))
        }
        else {
            res.set(StatusCode::TemporaryRedirect)
            //update header
            .set(Location("https://www.google.de".to_owned()));
            Ok(Halt(res))
        }
    }
}
```

Keep in mind: This is dummy code. I don't intend to check for a session variable from the query string for realz ;)

The problem is that I want to call `Halt` in the `else` arm but the way I wrote it leaves me with the following error message.

```
src/auth.rs:17:21: 17:24 error: mismatched types:
 expected `nickel::response::Response<'_, hyper::net::Streaming>`,
    found `nickel::response::Response<'a>`
(expected enum `hyper::net::Streaming`,
    found enum `hyper::net::Fresh`) [E0308]
src/auth.rs:17             Ok(Halt(res))
```

It seems the types don't match up but I have no idea why...

**Comment by Ryman** [comment]
The error message doesn't show the default type params clearly (it's what is added in the extra expected part, `Streaming` vs `Fresh`). :( 

You need to initiate the response to get it to start streaming, so the else branch should be something like:

```rust
res.set(..);
let stream = try!(res.start());
Ok(Halt(stream))
```

You would get those last two lines in essence if you did something like `res.send("Redirecting you to ..")` instead.

Also, if you're writing Auth, have you taken a look at https://github.com/nickel-org/nickel-auth/pull/1?

**Comment by cburgdorf** [comment]
Ah, ok! Thank you!

>Also, if you're writing Auth, have you taken a look at nickel-org/nickel-auth#1?

Yes, I noticed and I probably test it out quite soon. I just need to work through the very basics to understand the whole process before I build up on provided abstractions :)

I need to clean up my code and get rid of some hardcoded secrets and once that's done I may be able to make it public or at least give you access to it so that we have a real world use case that may help to drive session/auth support in nickel. The use case that I have also does OAuth integration with the GitHub API.

/cc @PascalPrecht
