### ISSUE TITLE
Create mounting middleware

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/nickel.rs#259]
Currently our `StaticFileHandler` middleware can't play out it's full strength because every path that one registers will become relative available to root (`/`). Which isn't alway what we want.

We need some sort of mounting middleware (e.g. https://github.com/iron/mount) that allows to bind the contents of a path to any subpath. E.g. you may want to bind `/css` to `my/area/css` which isn't possible right now.

**Comment by SimonPersson** [comment]
I think you can stick the current static files middleware in the router and
have it on whatever path you want, no? Perhaps we could document that just
:)

**Comment by cburgdorf** [comment]
You mean like [this](https://github.com/cburgdorf/nickel.rs/commit/d487ca017a957240ffe8530b7f499b00c81a6ee1)? This doesn't work :-/

**Comment by cburgdorf** [comment]
ping @SimonPersson ;)

Would love to this sorted (either by documenting, fixing or building something) for an 1.0 release.

**Comment by SimonPersson** [comment]
Yeah, I didn't think my previous comment through really, hehe :)

I'll give this a shot sometime next week if I'm not beaten to it. I just moved across the continent so I'm a bit busy the next couple of days.

**Comment by Ryman** [comment]
@cburgdorf Can we close this now?

**Comment by cburgdorf** [comment]
I haven't had the chance to integrate that in classroom yet but I assume it works and will reopen new issues that I may come across when I start with the integration.
