### ISSUE TITLE
Make Hyper's SSL feature optional

### ISSUE THREAD

**Issue by ixjf** [nickel-org/nickel.rs#274]
Since I'm on Windows, I would have to install MinGW and OpenSSL in order to build the library, even though I'm not going to use the feature. The Iron framework already allows to disable this feature, and not implying that you should follow the same footsteps, but it would be really nice. If HTTPS support was added at a later point, then that would be disabled along with SSL.

**Comment by Ryman** [comment]
This landed in 0.7
