### ISSUE TITLE
how to I can organize my layouts {{> layouts/footer }}

### ISSUE THREAD

**Issue by marti1125** [nickel-org/nickel.rs#279]
similar to following image
<img width="226" alt="screen shot 2015-09-08 at 11 33 21" src="https://cloud.githubusercontent.com/assets/223240/9740998/7c354f72-561d-11e5-828a-453801ee90da.png">

**Comment by Ryman** [comment]
This might be an issue with [mustache](https://github.com/nickel-org/rust-mustache). I'm guessing you'd need to be able to specify alternate search paths for partials.

I'm guessing you're wanting to imitate how rails (or another framework) layouts work?

**Comment by marti1125** [comment]
I am trying something similar to expressjs...

**Comment by Ryman** [comment]
Potentially relevant link for anyone wanting to implement this: https://github.com/publicclass/express-partials

**Comment by marti1125** [comment]
in this case how to I could implement this in nickel.rs?

**Comment by Ryman** [comment]
Well, it'll may need some changes to `mustache`, but I could imagine you can add a trait with a method `render_with_layout(..) -> MiddlewareResult` and implement it for `Response`. Then when you import that trait into scope, you can do `res.render_with_layout("template", &data, "myLayout")` within the handler. I'm sure there are some quirks that would need to be ironed out, but that's how I'd probably approach it.

I'd be happy to help if you get stuck or need something checked :space_invader:

**Comment by marti1125** [comment]
Hi, @Ryman could you help me? please

**Comment by Ryman** [comment]
@marti1125 Sorry, this fell off my radar, I'll see if I can get round to testing something like the above soon

**Comment by Ryman** [comment]
@marti1125 I've implemented basics of this out of the core tree (so we can iterate on it quicker), feature requests are welcome: https://crates.io/crates/nickel_mustache
