### ISSUE TITLE
Ability to disable mimetype-guessing for send_file

### ISSUE THREAD

**Issue by untitaker** [nickel-org/nickel.rs#285]
The file has no file extension, but I know the mimetype.

Some ideas:

* Use `set_header_fallback` inside `send_file` so I can set the header beforehand
* Implement `Responder` for file objects, change `send_file` to build the mimetype guessing on top of that.

**Comment by Ryman** [comment]
@untitaker The first suggestion sounds worth doing regardless, would you like to PR that change?

I've considered implementing Responder for `File/Path` before, but I can't remember what was iffy about that, it might be worth investigating again :)
