### ISSUE TITLE
some thing like a BeforeMiddleware (or a pre-middleware)

### ISSUE THREAD

**Issue by masoodahm** [nickel-org/nickel.rs#292]
hi, I know in nickel a middlware have a different meaning than other frameworks, but is there a mechanism to have a function that runs before every get and post to check if the user is logged in or not, if he/she is then continue to the handler else redirect to login

**Comment by SimonPersson** [comment]
You can write a middleware that wraps a middleware. See [mount](http://docs.nickel.rs/nickel/struct.Mount.html) for an example that does more or less what you're looking for.

Also, we are working on an auth middleware. You may want to check it out although it is not entirely ready yet: https://github.com/Ryman/nickel-auth/tree/current_user.

**Comment by Ryman** [comment]
@masoodahm Can we close this?

**Comment by masoodahm** [comment]
oh yes, for any one looking for similar solution, you can do 
```rust
server.get("**", middleware!{ |res, req| -> {
    //check for login here 
    // ...
    if loggedIn {
        Ok(Continue(res))
    }
    else {
        res.redirect("/login")
    }
});

server.get("/login", middleware! {}); // whatever login middleware goes here
// other routes defined here
```
the "**" middleware will run before all routes and redirect if necessary, otherwise continue to appropriate middleware.

**Comment by Ryman** [comment]
@masoodahm Thanks for the example!
