### ISSUE TITLE
Duplicate url build

### ISSUE THREAD

**Issue by djKooks** [nickel-org/nickel.rs#300]
Hello,
When running cargo build, why are there 2 versions of url being compiled?

Compiling url v0.5.0
Compiling url v0.2.38

**Comment by Ryman** [comment]
Published 0.7.3, which hopefully shouldn't cause this problem. Sorry!

Let me know if you've still got an issue!

**Comment by djKooks** [comment]
@Ryman 
It goes well. Thanks!
