### ISSUE TITLE
Support non-'static middleware?

### ISSUE THREAD

**Issue by euclio** [nickel-org/nickel.rs#307]
Hi all,

I'm currently using nickel.rs in my markdown preview server [aurelius](https://github.com/euclio/aurelius). One problem I'm running into is that I want to serve static files dynamically.

Imagine the following directory structure:
```
foo/
   bar.md
   img.png
baz/
   img2.png
```

If I start my server in the `foo`, I would I want to serve static files (`./img.png`) out of `foo`. However, I would like to be able to change the "working directory" of the server. So say I change a member of my server struct representing the working directory to be `baz`. Then my middleware will serve files (`./img2.png`) out of `baz`.

I attempted to do this by making my own version of the `StaticFilesHandler` that retrieves its root directory from an enclosing struct instead of when the middleware is initialized. However, I'm having trouble getting it to compile. I think this is due to the `'static` bound on the middleware.

Example code (does not compile):
```rust
server.utilize(middleware! { |request, response|
      let path = request.path_without_query().map(|path| {
          path[1..].to_owned()
      });

      if let Some(path) = path {
          let path = self.cwd.join(path);
          match fs::metadata(&path) {
              Ok(ref attr) if attr.is_file() => return response.send_file(&path),
              Err(ref e) if e.kind() != NotFound => debug!("Error getting metadata \
                                                            for file '{:?}': {:?}",
                                                            path, e),
              _ => {}
          }
      }; 
});
```

**Comment by cburgdorf** [comment]
Not sure if I get what you mean. You can set the directories to serve with the `StaticFileHandler` dynamically on startup just fine.

That's from my own projects code

```rust
for workshop in classroom_idx.get_workshops().values() {
        server.utilize(StaticFilesHandler::new(format!("{}/{}/{}", config::SLIDES_CLONEPATH, &workshop.id, &workshop.assets)));
    }
```

Or do you want to swap them after `listen` was already called?

**Comment by euclio** [comment]
The latter. I want to be able to change the directory at runtime after the server has started.

**Comment by cburgdorf** [comment]
Ah ok, never tried that. But this compiles just fine.

```rust
    server.get("/", middleware! { |req, mut res|
        StaticFilesHandler::new(req.param("DONT_DO_THIS").unwrap());
    });
```

**Comment by euclio** [comment]
Yes, but it's not quite what I want. That requires me to make a request to change the directory.

**Comment by cburgdorf** [comment]
It was just an easy demo that it should be possible to add directories at runtime. Need to look into your case later.

**Comment by euclio** [comment]
Whoops, realized that I can use `Arc<Mutex<_>>` to achieve this. Closing.
