### ISSUE TITLE
Upgrade to Hyper 0.8

### ISSUE THREAD

**Issue by cybergeek94** [nickel-org/nickel.rs#318]
I'd like to add support for Nickel in [multipart](https://github.com/cybergeek94/multipart) but we're currently on Hyper 0.7 over there, with [some pressure to upgrade to 0.8](https://github.com/LukasKalbertodt/telegram-bot/pull/34#issuecomment-199257644). Is there a reason you guys are so far behind?

**Comment by cburgdorf** [comment]
Would you be willing to handle the upgrade to latest hyper in a separate PR
before? I'm not sure if there's anything holding us from doing it. @Ryman?
Am 21.03.2016 20:57 schrieb "Austin Bonander" <notifications@github.com>:

**Comment by cybergeek94** [comment]
It doesn't look like there's any potential blockers, unless Nickel has its own `NetworkStream` implementatinon.

**Comment by Ryman** [comment]
No reason other than it would require a version bump (which would have been nice to coincide with some other breaks) and that there wasn't anything major added other that dependency bumps afaik.

Thanks for taking the action here @cybergeek94!

**Comment by Ryman** [comment]
This has been done in 0.8, thanks for your help @cybergeek94!
