### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by lxy254069025** [nickel-org/nickel.rs#320]
/Users/luxixi/.cargo/registry/src/github.com-88ac128001ac3a9a/aho-corasick-0.5.0/src/autiter.rs:4:22: 4:29 error: unresolved import `memchr::memchr2`. There is no `memchr2` in `memchr`. Did you mean to use `memchr`? [E0432]
/Users/luxixi/.cargo/registry/src/github.com-88ac128001ac3a9a/aho-corasick-0.5.0/src/autiter.rs:4 use memchr::{memchr, memchr2, memchr3};
                                                                                                                       ^~~~~~~
/Users/luxixi/.cargo/registry/src/github.com-88ac128001ac3a9a/aho-corasick-0.5.0/src/autiter.rs:4:22: 4:29 help: run `rustc --explain E0432` to see a detailed explanation
/Users/luxixi/.cargo/registry/src/github.com-88ac128001ac3a9a/aho-corasick-0.5.0/src/autiter.rs:4:31: 4:38 error: unresolved import `memchr::memchr3`. There is no `memchr3` in `memchr`. Did you mean to use `memchr`? [E0432]
/Users/luxixi/.cargo/registry/src/github.com-88ac128001ac3a9a/aho-corasick-0.5.0/src/autiter.rs:4 use memchr::{memchr, memchr2, memchr3};
                                                                                                                                ^~~~~~~
/Users/luxixi/.cargo/registry/src/github.com-88ac128001ac3a9a/aho-corasick-0.5.0/src/autiter.rs:4:31: 4:38 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `aho-corasick`.

To learn more, run the command again with --verbose.

**Comment by Ryman** [comment]
`cargo update` should fix this, looks like you picked up a broken version of `aho-corasick`.
