### ISSUE TITLE
Immediate thread exhaustion during surges of more than 100 requests per second

### ISSUE THREAD

**Issue by jkcdarunday** [nickel-org/nickel.rs#333]
Are there any updates on #309 ? It seems that thread exhaustion immediately occurs when you have thousands of requests in a second where each client has around ~200ms ping (each thread probably blocks for 200ms while waiting for I/O) which makes it not viable for medium to large scale websites that have sudden surges of traffic time by time. This is just an observation though so I'm not sure if my conclusion is true.

**Comment by Ryman** [comment]
I'd recommend reverse-proxying behind nginx if you need to handle slow clients with a decent amount of load (until nickel becomes async at least), but we've now released 0.8.1 which has [options to adjust thread usage](https://github.com/nickel-org/nickel.rs/blob/master/src/nickel.rs#L24-L26) which should hopefully help alleviate the problem. Please re-open if it doesn't fix your issues!
