### ISSUE TITLE
How to block until server is ready to listen?

### ISSUE THREAD

**Issue by euclio** [nickel-org/nickel.rs#340]
I'm working on a markdown preview server library that starts a local nickel server to display HTML. I *think* I'm running into a race condition where it's possible to send requests to the server before it's actually up and running. Since calling `server.listen()` consumes the current thread, I'm not sure how to actually know when the main thread is able to start sending requests to the server.

Is it possible to do this in the current release? Or does #334 provide a way to do this?

**Comment by Ryman** [comment]
I think #334 is along the lines of something that you'd need (feel free to let us know if it isn't!). I'm not sure if there's a clean way to do it from within the same process in current master, in our tests we had to spawn subprocesses and read from stdout to handle this kind of thing. (yuck)

**Comment by euclio** [comment]
Tested out the PR in my project, and it works perfectly! I'll close this issue when the PR is merged.

**Comment by kellpossible** [comment]
You going to close this? It looks like it was merged.
