### ISSUE TITLE
hello world without middleware! macro

### ISSUE THREAD

**Issue by ctaggart** [nickel-org/nickel.rs#346]
I'm trying to see if I can get the gdb debugging to work in Visual Studio Code so that it breaks on a HTTP GET request. I don't think it is going to work with macros. I haven't done a ton of Rust programming yet and I'm not sure how to turn the `middleware!` macro into actual code. It would be great if I could create a separate function such as `fn get_foo`. How do I code with without the `middleware!` macro? Is there an easy way to see what the macro produces?

``` rust
#[macro_use] extern crate nickel;
extern crate hyper;

// http://docs.nickel.rs/nickel/router/http_router/trait.HttpRouter.html

use nickel::{Nickel, MediaType, HttpRouter};
use hyper::method::Method::{Get, Post, Put, Delete};

fn main() {
    let mut server = Nickel::new();
    server.add_route(Get, "/foo", middleware! { "Get request! "});
    server.listen("127.0.0.1:6767");
}
```

![image](https://cloud.githubusercontent.com/assets/80104/15954427/cdeb9c1c-2e8b-11e6-9e48-025e2602fe39.png)

**Comment by Ryman** [comment]
If the important aspect of your testing is to break in the middle of the HTTP request, you should be able to use the [non-macro example](https://github.com/nickel-org/nickel.rs/blob/master/examples/hello_world.rs). 

If you want to further your test and ensure it works with closures then you'll need to do something with type hints. (Just in case you didn't know already, if you need to expand the example with macros you can do `cargo rustc --example hello_world_macro -- --pretty=expanded -Z unstable-options`.)

The expansion of hello world with macros is: (note that the expansion code secretly uses features which are inserted by the compiler, so you'll need a nightly compiler if you want to copy and run it... or remove the feature usage!)
```rust
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std as std;
#[macro_use]
extern crate nickel;

use nickel::{Nickel, HttpRouter};

fn main() {
    let mut server = Nickel::new();
    server.get("**",
               {
                   use ::nickel::{MiddlewareResult, Responder, Response,
                                  Request};
                   #[inline(always)]
                   fn restrict<'mw, D,
                               R: Responder<D>>(r: R, res: Response<'mw, D>)
                    -> MiddlewareResult<'mw, D> {
                       res.send(r)
                   }
                   #[inline(always)]
                   fn restrict_closure<F, D>(f: F) -> F where F: for<'r, 'mw,
                    'conn>Fn(&'r mut Request<'mw, 'conn, D>, Response<'mw, D>)
                    -> MiddlewareResult<'mw, D> + Send + Sync {
                       f
                   }
                   restrict_closure(move |_, _res| {
                                    restrict({ "Hello World" }, _res) })
               });
    server.listen("127.0.0.1:6767");
}
```

`restrict` was used for ergonomics, if the return type implements `Responder` then that's _OK_ while still allowing the user to return a full `MiddlewareResult` if they want (via an early return in the expansion). We can ignore it for the purpose of this issue.

`restrict_closure` is the real ugly belly of the `middleware!` macro. It ensures that the body of the macro has the correct signature and (generally) coerces any bad inference of lifetimes to be what we need for `Middleware`. (you can see a lot of failed inference if you try to use a closure in place of where `middleware!` is used currently)

If you want to get closures working in a simple setting you'll want to implement something similar to `restrict_closure` in order for things to work out. (or just use the simpler `fn` method in the linked example if you don't care about closures!)

If I've skimmed over anything you want more information or a better explanation of, feel free to ask.

**Comment by ctaggart** [comment]
Thanks @Ryman! That non-macro example is exactly what I was looking for. It does indeed hit the breakpoint now. I was hoping to be able to view the Request object, but trying to expand self resulted in a 
```
Python Exception <type 'exceptions.TypeError'> Could not convert Python object: None.
```
![image](https://cloud.githubusercontent.com/assets/80104/15971833/003f79e0-2ef0-11e6-92dc-b04f63401d49.png)

I'll troubleshoot and log a bug elsewhere.
