### ISSUE TITLE
Binary example

### ISSUE THREAD

**Issue by maxfridbe** [nickel-org/nickel.rs#347]
Would it be possible to have an example of a response of a binary like image/jpeg

**Comment by Ryman** [comment]
Are you specifically interested in an example that shows explicitly setting the content type header or one that just leaves the burden on `send_file` which does some checks based on filename?

Also, the [static_files example](https://github.com/nickel-org/nickel.rs/blob/master/examples/static_files.rs) is  serving a folder containing jpegs if that's what you need.

**Comment by maxfridbe** [comment]
Excuse my c#, but this I essentially just want to know how to return bytes/streams and set headers.  I have looked at the static files example but I am a newbie to rust and cannot follow all the work being done to serve up a whole directory vs one simple file request.  I am trying to just make a test imagemagik app.
```c#
[HttpGet]
    public HttpResponseMessage Resize(string source, int width, int height)
    {
        HttpResponseMessage httpResponseMessage = new HttpResponseMessage();

        // some image operation
        Image image = Photo.Resize(Image.FromFile(@"d:\path\" + source), width, height);
        MemoryStream memoryStream = new MemoryStream();
        image.Save(memoryStream, ImageFormat.Jpeg);

       //some way to set a response stream
        httpResponseMessage.Content = new ByteArrayContent(memoryStream.ToArray());

        httpResponseMessage.Content.Headers.ContentType = new MediaTypeHeaderValue("image/jpeg");
        httpResponseMessage.StatusCode = HttpStatusCode.OK;

        return httpResponseMessage;
    }
```

**Comment by Kilte** [comment]
You can send a file using [this](https://github.com/nickel-org/nickel.rs/blob/master/src/response.rs#L129) method.
But as you can see, it works with FS only. So you need [copy](https://github.com/nickel-org/nickel.rs/blob/master/src/response.rs#L143) data to stream manually.

**Comment by maxfridbe** [comment]
Thank you I was able to return an image via this code:

```rust
fn handler<'a, D>(_: &mut Request<D>, res: Response<'a, D>) -> MiddlewareResult<'a, D> {
     let p = Path::new("test.png");
     res.send_file(&p)
 }
```

If i could ask one more question or request one more example.  How do i perform a file upload akin to:

```c#
[HttpPost, Route("api/upload")]
public async Task<IHttpActionResult> Upload()
{
    if (!Request.Content.IsMimeMultipartContent())
        throw new HttpResponseException(HttpStatusCode.UnsupportedMediaType); 

    var provider = new MultipartMemoryStreamProvider();
    await Request.Content.ReadAsMultipartAsync(provider);
    foreach (var file in provider.Contents)
    {
        var filename = file.Headers.ContentDisposition.FileName.Trim('\"');
        var buffer = await file.ReadAsByteArrayAsync();
        //Do whatever you want with filename and its binaray data.
    }

    return Ok();
}

```

**Comment by Kilte** [comment]
@maxfridbe AFAIK, nickel does not support `multipart/form-data`. You can try this crate: https://github.com/cybergeek94/multipart

**Comment by jolhoeft** [comment]
The multipart crate (https://crates.io/crates/multipart) provides `multipart/form-data` support, which can be used to upload binary data as a part of a form. In the http PUT case, `req.origin.read_to_end` can be used to read the binary data.
