### ISSUE TITLE
Depend on url > 0.5.9 in Stable nickel release

### ISSUE THREAD

**Issue by cengizIO** [nickel-org/nickel.rs#361]
Hello there!

First of all, I'd like to share my love for nickel.rs 👍 😍 👍 

It's super simple and fun to work with!

Your [0.8.1 version on crates.io](https://crates.io/crates/nickel/0.8.1) depends on a very old version of `url` crate.

In that version, `url`'s `Cargo.toml` has a spec violating line which will throw errors in a future release of Rust.

```
# in a project directory, which depends on nickel-0.8.1

$ cargo tree
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading nickel v0.8.1
 Downloading plugin v0.2.6
 Downloading mustache v0.6.3
 Downloading rustc-serialize v0.3.19
 Downloading url v0.5.9
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/canc/.cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.9/Cargo.toml`

Caused by:
  could not parse input as TOML
/Users/canc/.cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.9/Cargo.toml:14:3 expected a newline after table definition

error: third party subcommand `cargo-tree` exited unsuccessfully
```

As far as I see in `url` history, this violation [was fixed](https://github.com/servo/rust-url/commit/e362e1382784ccf455533183fde0d12666aa3fac) in recent releases.

And it seems that your `Cargo.toml` in `master` branch already points to `url-1.0.0`

What's the best approach here?

Regards

**Comment by jolhoeft** [comment]
We are now depending on url-1.0, so this should be resolved.
