### ISSUE TITLE
Upgrade to Hyper 0.9

### ISSUE THREAD

**Issue by abonander** [nickel-org/nickel.rs#367]
Blocking https://github.com/cybergeek94/multipart/issues/44

**Comment by zpallin** [comment]
https://github.com/nickel-org/nickel.rs/commit/b77e4ca9a5544a742ec2fb894b85b6b736239656

Looks like it got merged. 👍

**Comment by White-Oak** [comment]
@zpallin but it's not released, https://crates.io/crates/nickel 0.8.1 still has  `hyper = 0.8` as a dependency.

**Comment by zpallin** [comment]
@White-Oak Oh. I guess the crate wasn't published, cause the commit I mentioned is on the master branch.

**Comment by White-Oak** [comment]
@zpallin multipart is also published on crates.io, that requires that dependencies of a crate are from the same place (from crates on crates.io in our cases). So to update multipart's hyper dependency on crates.io, first, nickel's hyper dependency should be updated on crates.io.

Or, as specified in #368, if nickel was to reexport `hyper::server::Request` type, the right dependency would be propagated through/

PS: yeah, I mean if there is a hurry, there is a solution in specifying dependency to github directly, but released crates currently depend on hyper 0.8.

**Comment by White-Oak** [comment]
Also, #382 is related

**Comment by zpallin** [comment]
@White-Oak oh yea. I guess I could've seen that coming.

Where are the maintainers for this repo? I looked at @Ryman's github and he hasn't had activity for a month. Is he on vacation?

**Comment by cburgdorf** [comment]
I haven't been a good maintainer for this repo since a while. @Ryman and @SimonPersson have been more in charge for the last couple of months. That said, let me see if can figure out how to cut a release real quick :)

**Comment by cburgdorf** [comment]
There you go https://github.com/nickel-org/nickel.rs/commit/9c0894562cdc6298dafc4c38b22cb449efc6b5b3

Also live on https://crates.io/crates/nickel
