### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by pietroalbini** [nickel-org/nickel.rs#382]
There are a few useful changes in master which are not released yet, such as b77e4ca9a5544a742ec2fb894b85b6b736239656 and da7d52951c295e6f064c359e06c5a2e99d12c1f2. In order to use those I'm currently depending on the git repository, but that's not great. Would be possible to cut a new release soon*ish*?

Thank you!
Pietro.

**Comment by cburgdorf** [comment]
There you go https://github.com/nickel-org/nickel.rs/commit/9c0894562cdc6298dafc4c38b22cb449efc6b5b3

Also live on https://crates.io/crates/nickel

**Comment by pietroalbini** [comment]
Thank you for the release!

**Comment by cburgdorf** [comment]
You're very welcome!
