### ISSUE TITLE
http://docs.nickel.rs/ is down

### ISSUE THREAD

**Issue by rustybox** [nickel-org/nickel.rs#406]
Has been down for hours.

http://downforeveryoneorjustme.com/http://docs.nickel.rs/

**Comment by jolhoeft** [comment]
Domain has expired:

$ whois nickel.rs
%
%This is the RNIDS Whois server.
%
% Date Format : DD.MM.YYYY
% Whois Server Version: 1.0.0
%
% Rights restricted by copyright.
% See http://www.rnids.rs/whois_en
%
%
%
% Ovo je odgovor od RNIDS Whois servera.
%
% Format datuma : DD.MM.YYYY
% Verzija Whois Servera : 1.0.0
%
% Sva prava zadržana. Za više informacija.
% pogledajte http://www.rnids.rs/whois_sr

Domain name: nickel.rs
Domain status: Expired, clientUpdateProhibited
Registration date: 15.07.2014 21:42:05
Modification date: 07.04.2017 11:31:35
Expiration date: 15.07.2017 21:42:05
Registrar: NINET Company d.o.o.

**Comment by thomaskuntzz** [comment]
Can't access nickel.rs neither...

**Comment by freiguy1** [comment]
Is this project dying?

**Comment by jolhoeft** [comment]
The domain owner is having trouble communicating with the registar.

This project isn't dead. Pull requests are always welcome. :-)

**Comment by eltomito** [comment]
Can I find the documentation anywhere in the meantime, please?

**Comment by Kilte** [comment]
@eltomito API documentation available here: https://docs.rs/nickel/0.10.0/nickel/

**Comment by cburgdorf** [comment]
Does anyone know a modern registrar for .rs domains? I'd happy to migrate it to something where we actually have direct control and not just spontaneous email support.

**Comment by brechtpm** [comment]
https://eurodns.com has them, though the .rs domains do look quite pricey there.

**Comment by therealbstern** [comment]
To save others some research:

Neither of my first choice registrars, OpenSRS and NSI, will register `.rs` right now.  Nor will Amazon nor GoDaddy.  Without vouching for either one of these right now, eurodns is  €98.00/year and Gandi.net is $110/year.

**Comment by eltomito** [comment]
As I understand, .rs is the Serbian national domain. I googled for a Serbian domain registrar and I found this list of accredited registrars: https://www.rnids.rs/en/registrars/list-accredited-registrars
I tried the first one and you can switch it to English. I bet many of the others will work in English, too.
I'd go for those. The first one claims to charge 17.50 euros + VAT for domain registrations. It should be around 20E total.

**Comment by schepelin** [comment]
Guys do you need a donation for the domain? Please, post your send your PayPal or card number here and I'll donate

**Comment by jolhoeft** [comment]
Just fixed by [@cburgdorf](https://github.com/cburgdorf)

**Comment by cburgdorf** [comment]
First off, sorry for the lack of communication from my part. I've updated the link in the readme to point to http://nickel-org.github.io/ and removed the CNAME files. Means, the website is back online just without the fancy .rs domain. If anyone feels like stepping in to provide a nice top level domain again, please feel free to do so. Changing the CNAME file is easy.
