### ISSUE TITLE
There is a project official website?

### ISSUE THREAD

**Issue by phtdacosta** [nickel-org/nickel.rs#409]
Unfortunately, the link provided seems to be on sale or something,

**Comment by Kilte** [comment]
http://nickel-org.github.io/

**Comment by phtdacosta** [comment]
Thanks for the response! By the way, you guys could update it on the description of the following page **/nickel-org/nickel.rs** so others will not be confused too.

**Comment by jcbritobr** [comment]
I opened a new issue to do this work. Is a simple issue that can be solved in less than five minutes. Shame keep the description pointing to the wrong address.

**Comment by Ryman** [comment]
Sorry for the delay on this, it should be fixed now :)
