### ISSUE TITLE
fix wrong url address in project description

### ISSUE THREAD

**Issue by jcbritobr** [nickel-org/nickel.rs#411]
The project description is pointing to a wrong url address. This webpage dont exists. 
"An expressjs inspired web framework for Rust http://nickel.rs"

Need to fix it to be equal the ones in README.md

**Comment by jolhoeft** [comment]
We missed one of the entries in the README files, the first one, which I've just corrected. Is there somewhere else you are seeing a reference to the old url?

**Comment by jcbritobr** [comment]
@jolhoeft good morning.

I only see in description. Here is the screen capture:

![wrongurl](https://user-images.githubusercontent.com/6579862/32782499-c39fedae-c92f-11e7-9df0-32723e262c49.PNG)

**Comment by jolhoeft** [comment]
Wow, I had completely stopped even seeing that.

Unfortunately, I have commit access, but don't own the repository. Hopefully @Ryman, @cburgdorf , or @SimonPersson will see this.

**Comment by Ryman** [comment]
This should be fixed now :)
