### ISSUE TITLE
Docs Link is Broken

### ISSUE THREAD

**Issue by joshuamil** [nickel-org/nickel.rs#422]
Clicking on the API Docs link takes you to http://docs.nickel.rs/ which is one of those domain-provider listing pages rather than the actual documentation.

**Comment by jolhoeft** [comment]
Sorry, we missed one when we moved domains. Here is a current link, and I'll update the README.

https://docs.rs/nickel/0.10.1/nickel/

**Comment by jolhoeft** [comment]
I've updated the README and the API Docs link on the web pages. Some changes will take some time to propagate to crates.io. Let me know if you find more incorrect links. Thanks.
