### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by sameer** [nickel-org/nickel.rs#424]
I'm getting a page that looks like the domain was not renewed when I try to go to the site. Is it down?

**Comment by jolhoeft** [comment]
We no longer own the nickel.rs website. The new website is http://nickel-org.github.io/. The link at the top of the github page is wrong, which I am trying to get fixed. Have you seen others I've missed?

**Comment by sameer** [comment]
@jolhoeft Github repo description, looking for other places.

**Comment by sameer** [comment]
Nevermind, I see that this was mentioned in another issue. Closing.
