### ISSUE TITLE
[Site] Site url doesn't exist

### ISSUE THREAD

**Issue by andresmargalef** [nickel-org/nickel.rs#425]
The url [http://docs.nickel.rs/nickel/](http://docs.nickel.rs/nickel/) shows this page

![image](https://user-images.githubusercontent.com/6145226/35080013-b6ed754e-fbe9-11e7-878b-705d146eb991.png)

**Comment by jolhoeft** [comment]
Yes, we no longer own nickel.rs. The site is now http://nickel-org.github.io/. Did you find a link to the old one? I thought I'd gotten them all, but I've thought that several times now and been wrong.

**Comment by vimal7370** [comment]
'API Docs' button at http://nickel-org.github.io/ points to that dead link.

**Comment by Ryman** [comment]
Thanks for the report @vimal7370, looks like @jolhoeft took care of this https://github.com/nickel-org/nickel-org.github.io/commit/d4320eaf7d44400fa19b05c48019f79a1e62478f

Thanks @jolhoeft!
