### ISSUE TITLE
How to handle form body ?

### ISSUE THREAD

**Issue by clintnetwork** [nickel-org/nickel.rs#443]
Hey,

I would like to know how to get the raw body ?

Thanks

**Comment by jolhoeft** [comment]
The raw body, or do you want the form parsed? [examples/form_data/form_data.rs](https://github.com/nickel-org/nickel.rs/blob/master/examples/form_data/form_data.rs) shows how to read the parsed form parameters. It also has some examples of functions that auto-implement the `Middleware` trait (for issue #442).

**Comment by clintnetwork** [comment]
Thank you
