### ISSUE TITLE
Missing .head() method in Nickel::router()

### ISSUE THREAD

**Issue by clintnetwork** [nickel-org/nickel.rs#444]
Hi,

I try to create a REST API with Nickel, and I've some difficulties to implement head method.

Could you add `router.head()` to the Nickel Router ?

Thank you!

**Comment by jolhoeft** [comment]
I don't see a reason for there not to be one. I guess no one has needed it before now. I'll add it shortly. In the meantime, you ought to be able to use this -

```rust
  router.add_route(Method::Head, matcher, handler);
```

- which is what the implementation will be.

**Comment by clintnetwork** [comment]
Yes yes it works like this, but it can be good to add directly .head()

Thanks

**Comment by jolhoeft** [comment]
Re-opening, to remind myself to implement his.

**Comment by jolhoeft** [comment]
We have a PR - #447

**Comment by jolhoeft** [comment]
And merged. I'm going to see if I can get anything else in this week, then push a new version to crate.io on Saturday.
