### ISSUE TITLE
Can't start server at 127.0.0.1

### ISSUE THREAD

**Issue by Ragueel** [nickel-org/nickel.rs#445]
I wasn't able to start server at `127.0.0.1` when my computer did not had connection to any network. But writing `localhost` seems to work. Is this design choice?

**Comment by clintnetwork** [comment]
Works no me!

```rust
endpoint: format!("127.0.0.1:7021"),
```

**Comment by jolhoeft** [comment]
To clarify, under Windows, with wifi off, the following fails as above:

```rust
let mut server = Nickel::new();
server.listen("127.0.0.1:5010");
```

but this would work?

```rust
let mut server = Nickel::new();
server.listen("localhost:5010");
```

This is rather puzzling. What version of windows are you using? I presume turning the wifi back on fixes this?

**Comment by Ragueel** [comment]
I found out the issue. It was one of my custom `middleware` that tried to access the internet and thus caused errors when I tried to register it. After removing it everything works. Sorry :)
