### ISSUE TITLE
How tu set utf-8 ?

### ISSUE THREAD

**Issue by clintnetwork** [nickel-org/nickel.rs#449]
Hi,

I currently create a KV store with an HTTP API ([lucid](/clintnetwork/lucid)) and I return a `Vec<u8>` with the `res.send(value)` method, but when I check the URL, some emoji does not works, and the encoding is `windows-1252`.

How can I set UTF-8 ?

Thanks!

**Comment by clintnetwork** [comment]
I specify that I set by default: `res.set(MediaType::Txt)`

**Comment by clintnetwork** [comment]
Yes with Json output, I don't have this problem 😂

**Comment by clintnetwork** [comment]
So the question is, how to set a generic mimetype, that display text or json when it's the case and display image when its the case too, and does not download a file without extension ? 😁

**Comment by jolhoeft** [comment]
`res.send` takes something that implements the `Responder` trait, which has several default implementations. `Vec<u8>` sets its media type to `MediaType::Bin`, while `String` uses `MediaType::Html`. I think the easiest approach would be to convert the `Vec<u8>` to a `String` with `String::from_utf8` or `String::from_utf8_lossy`

**Comment by clintnetwork** [comment]
Do you sleep sometimes? ^^

**Comment by clintnetwork** [comment]
Also, how to set a custom mime type like `text/csv` or other directly from string without `MediaType` type ?

**Comment by jolhoeft** [comment]
It's only 7pm here in Seattle :-)

If you set the `MediaType` explicitly, the automatic setting should be skipped. `res.set(MediaType::Csv)` ought to work. Let me know if it doesn't. There may be a bug.

**Comment by clintnetwork** [comment]
Yes but justly, how to do it, how to set the mime-type from a string?

**Comment by jolhoeft** [comment]
From within the String, you can't. You need something like this:

```rust
data = "some, data\nmore,data\n".to_string();
res.set(MedisType:Csv);
res.send(data)
```

**Comment by clintnetwork** [comment]
Thank you
