### ISSUE TITLE
About https and hyper-openssl

### ISSUE THREAD

**Issue by clintnetwork** [nickel-org/nickel.rs#450]
Hi,

The method `listen_https` require `hyper-openssl` crate, that require openssl locally installed on the computer, is it possible to bypass this ? or use an other way?

This is the error that I have:
```--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
note: vcpkg did not find openssl as libcrypto and libssl: Could not find Vcpkg tree: No vcpkg.user.targets found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'
note: vcpkg did not find openssl as ssleay32 and libeay32: Could not find Vcpkg tree: No vcpkg.user.targets found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'
```

The problem is I want to make a portable app, without ask people to install openssl or a lot of stuffs.

Thank you

**Comment by jolhoeft** [comment]
You'd need to implement the `hyper::net::SslServer` trait and use that instead. I would have to start digging to see if there are any pure Rust ssl crates. Any Ssl support is going to require some sort of certificate management, which will probably be more trouble than installing OpenSsl I'm afraid.

**Comment by clintnetwork** [comment]
Hmm okay, and what about `rust-openssl` ?

**Comment by clintnetwork** [comment]
Hmm, I will see ^^
