### ISSUE TITLE
Wildcards break on encountering the @ symbol

### ISSUE THREAD

**Issue by MeguminSama** [nickel-org/nickel.rs#456]
example:

`server.get("/**", middleware!{........});`

this works fine for most paths, my.site/path/to/file
but if there is an `@` in the url it decides to 404 for some reason. e.g. `my.site/path/@to/file`

**Comment by jolhoeft** [comment]
The `**` matches on the regex `[,/a-zA-Z0-9_-]*`, so it doesn't match anything with `@` in it. Instead of a string, you can route on a regex; see the `regex_route.rs` example.

**Comment by MeguminSama** [comment]
I somehow missed that! Thank you very much!
