### ISSUE TITLE
What happened to this masterpiece?

### ISSUE THREAD

**Issue by suyashjawale** [nickel-org/nickel.rs#464]
Why is this project abandoned?

**Comment by jolhoeft** [comment]
A shortage of volunteers I'm afraid. I have a version at the head of master that is mostly ported to hyper 0.14.x. I just need to find some time to finish that up and release it.

**Comment by suyashjawale** [comment]
Ohh, i am not smart enough to contribute. But i have starred it to show support. Wish you luck.
