### ISSUE TITLE
nickel-demo compile error

### ISSUE THREAD

**Issue by Linicks** [nickel-org/nickel.rs#55]
Following the demo steps on the nickel.rs website went well until I got this compiler error:

-->  error: linking with `cc` failed: exit code: 1

Once I installed libssl-dev, the demo compiled correctly and ran.  You may want to consider adding this to the notes, or check for it in your code.

Was testing on Ubuntu 14.04 Desktop.

-Thanks!
-- Nick

**Comment by Ryman** [comment]
Assuming this is no longer an issue with cargo, closing.
