### ISSUE TITLE
implement handling of form data

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/nickel.rs#7]

**Comment by daogangtang** [comment]
??? any progress???

**Comment by daogangtang** [comment]
nickel couldn't parse http form body now, why???

**Comment by cburgdorf** [comment]
Sorry, we didn't implement form data handling yet. Maybe your first contribution to the project?

**Comment by daogangtang** [comment]
ok, let me try.

**Comment by Ryman** [comment]
@daogangtang You may be interested in https://github.com/cybergeek94/multipart (but afaik it would have slight issues as it requires taking ownership of the Request currently)

**Comment by gkbrk** [comment]
I have used [rust-url](https://github.com/servo/rust-url) to handle POST data from forms in a project. You can see my example use [here](https://gist.github.com/gkbrk/40aa741ad744b46449bf#file-main-rs-L37-L41) and [here](https://gist.github.com/gkbrk/40aa741ad744b46449bf#file-main-rs-L85-L92).

**Comment by waqqas-abdulkareem** [comment]
Has there been any work done on this issue? I've never contributed to an open source project before and I'd be interested on having a go.

**Comment by cburgdorf** [comment]
That would be a perfect opportunity to make your first contribution ;) 

You may just start a PR and we iterate together until it's ready.

**Comment by jolhoeft** [comment]
This appears to have been added in commit f3d194a8e43a1eb5f5ae660bcf2f7e2c3c6bcb39
