### ISSUE TITLE
Type  safety for Request/Middleware

### ISSUE THREAD

**Issue by SimonPersson** [nickel-org/nickel.rs#79]
The following code builds today:

    extern crate nickel_postgres;
    extern crate nickel;

    use std::io::net::ip::Ipv4Addr;
    use self::nickel::{Nickel, Request, Response, JsonBody};
    use nickel_postgres::{ PostgresMiddleware, PostgresRequestExtensions };

    fn main() {
        let mut server = Nickel::new();
        fn db_handler(req: &Request, response: &mut Response)
        {
            let db_conn = req.db_conn();
            response.send("doesn't work");
        }
        let mut router = Nickel::router();
        router.get("/", db_handler);

        server.utilize(router);
        server.listen(Ipv4Addr(127, 0, 0, 1), 6767);
    }

`db_handler()` will never be able to retrieve a database connection since we haven't utilized a PostgresMiddleware and we will get a crash at every request.

In my opinion, the whole point of writing web applications in a statically typed language is that the compiler will catch this kind of bugs for us. With the current situation we're no better than Python/Ruby/Whatever in that regard.

Could we discuss some approaches to solving this? I have some ideas that I'm going to try out but I'd like to hear some more thoughts on this too.

**Comment by cburgdorf** [comment]
Closing as part of a clean up of our issue tracker. Anyone please free to reopen for further discussion.
