### ISSUE TITLE
alternative to 'utilize'

### ISSUE THREAD

**Issue by qshane** [nickel-org/nickel.rs#85]
Is there a reason `.utilize()` is used instead of `.use()`? 'Utilize' is a bit of an ugly filler word, and it's (perhaps) needlessly different from Express and other frameworks.

**Comment by ninjabear** [comment]
maybe ```add```? I think I prefer ```using``` but I thought I'd throw that in the ring. 
 
```{rust}
nickel.add(routes!(...));
```

**Comment by cburgdorf** [comment]
Closing as part of a clean up of our issue tracker. Anyone please free to reopen for further discussion.
