### ISSUE TITLE
Do we want to move middleware into different crates inside the same repo?

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/nickel.rs#88]
Just like we did with the macro.

 @Ryman @SimonPersson

**Comment by cburgdorf** [comment]
Closing as part of a clean up of our issue tracker. Anyone please free to reopen for further discussion.

**Comment by Ryman** [comment]
I think this is still worth pursuing in the `near future` or for a significant milestone, with the aide of something like [cargo-crusader](https://users.rust-lang.org/t/cargo-crusader-0-1-test-the-downstream-impact-of-rust-crate-changes-before-publishing/2373) running on travis
