### ISSUE TITLE
fails to compile with latest nightly

### ISSUE THREAD

**Issue by jacek99** [nickel-org/nickel.rs#97]
Just followed the steps in Getting Started with the latest Rust nightly:

nickel-demo$ cargo run
    Updating git repository `https://github.com/nickel-org/nickel.rs.git`
    Updating git repository `https://github.com/servo/rust-url.git`
    Updating git repository `https://github.com/lifthrasiir/rust-encoding`
    Updating git repository `https://github.com/Ryman/groupable-rs`
    Updating git repository `https://github.com/chris-morgan/rust-http.git`
    Updating git repository `https://github.com/sfackler/rust-openssl.git`
    Updating git repository `https://github.com/pythonesque/rust-mustache.git`
    Updating git repository `https://github.com/chris-morgan/anymap.git`
   Compiling rust-mustache v0.3.0 (https://github.com/pythonesque/rust-mustache.git#af44dbee)
   Compiling anymap v0.9.0 (https://github.com/chris-morgan/anymap.git#512885e5)
   Compiling openssl v0.0.0 (https://github.com/sfackler/rust-openssl.git#c407530d)
   Compiling groupable v0.1.0 (https://github.com/Ryman/groupable-rs#ae2a086e)
   Compiling encoding v0.1.0 (https://github.com/lifthrasiir/rust-encoding#ff55916f)
   Compiling nickel_macros v0.0.1 (https://github.com/nickel-org/nickel.rs.git#c1bb3e17)
   Compiling url v0.1.0 (https://github.com/servo/rust-url.git#55b18b79)
   Compiling http v0.1.0-pre (https://github.com/chris-morgan/rust-http.git#5bcd379e)
src/http/server/request.rs:50:23: 50:25 error: static variables cannot be referenced in a pattern, use a `const` instead
src/http/server/request.rs:50                 Ok(_b@SP) => continue,
                                                    ^~
error: aborting due to previous error
Could not compile `http`.

It seems to be in the http package, maybe it should get locked to a version that works?

**Comment by cevarief** [comment]
cargo run
... mod dummy { include!(concat!(env!("OUT_DIR"), "/read_method.rs")); }
Could not compile `http`.

rustc 1.0.0-nightly
